# This workflow will do a clean install of node dependencies, build the source code and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BuildCI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_android:
    name: Test build android app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Start flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      
  test_iOS:
    name: Test build iOS app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Start flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: pod install --project-directory=./ios; flutter build ios --target=./lib/main.dart --no-codesign
